src/main/java/com/example/demo/entity/User.java, src/main/java/com/example/demo/repository/UserRepository.java
@K-M0613 @mojito18 @m1k4226 
確認をよろしくお願いします。
=> UserEntityとUserRepositoryを作成

src/main/java/com/example/demo/repository/ReservationRepository.java, src/main/java/com/example/demo/repositpry/ReservationRepository.java
確認お願いします。
全員確認出来次第developへマージします。
=> Feature/reservation repository パッケージ名の修正とimport文の追加

src/main/java/com/example/demo/entity/Plan.java, src/main/java/com/example/demo/repository/PlanRepository.java
確認お願いします。
全員確認出来次第developへマージします。
=> PlanEntityとPlanRepositoryの作成

src/main/java/com/example/demo/repository/HotelRepository.java
確認お願いします。
全員確認出来次第developへマージします。
=> HotelRepository作成

src/main/java/com/example/demo/controller/HotelController.java, src/main/resources/templates/hotel.html
=> ホテル検索(TOP)表示

src/main/java/com/example/demo/controller/RegisterController.java, src/main/resources/templates/register.html, src/main/resources/templates/registerConfirm.html
@K-M0613 @mojito18 @m1k4226 
お疲れ様です。DBにふりかな項目追加に伴い、入力と確認画面に追加修正しました。
ご確認をお願い致します。
=> DB変更に伴い、ふりかなの入力・表示項目の追加しました

src/main/java/com/example/demo/controller/ReservationController.java
=> Accountモデルimport文追加

src/main/resources/templates/stayInfo.html
=> 申込者情報入力欄修正

src/main/java/com/example/demo/controller/ReservationController.java, src/main/java/com/example/demo/entity/User.java, src/main/resources/templates/confirmStayInfo.html, src/main/resources/templates/stayInfo.html
フリガナ入力フォームを追加しました。
処理に問題がないかの確認をお願いします。
確認ができたら、確認完了した旨のコメントをお願いします。
=> フリガナ入力フォーム追加

src/main/java/com/example/demo/entity/Reservation.java, src/main/resources/schema.sql
=> 予約テーブルに合計金額カラムを追加

build.gradle, src/main/java/com/example/demo/controller/RegisterController.java, src/main/java/com/example/demo/entity/User.java, src/main/java/com/example/demo/exception/EmailAlreadyExistsException.java, src/main/java/com/example/demo/repository/UserRepository.java, src/main/java/com/example/demo/service/UserService.java, src/main/java/com/example/demo/validator/FieldsValueMatch.java, src/main/java/com/example/demo/validator/FieldsValueMatchValidator.java, src/main/resources/static/CSS/completion.css, src/main/resources/static/CSS/form-common.css, src/main/resources/static/CSS/register-confirm.css, src/main/resources/templates/register.html, src/main/resources/templates/registerComplete.html, src/main/resources/templates/registerConfirm.html
@K-M0613 @mojito18 @m1k4226 
お疲れ様です。ご確認をお願い致します。
=> ユーザーの新規登録処理と遷移処理を追加、入力値とバリデーションを追加、エラーメッセージの表示処理を追加

src/main/java/com/example/demo/controller/ReservationController.java, src/main/java/com/example/demo/entity/Reservation.java, src/main/java/com/example/demo/model/Account.java, src/main/resources/templates/completeStayInfo.html, src/main/resources/templates/confirmStayInfo.html, src/main/resources/templates/stayInfo.html
予約完了機能を追加しました。ご確認よろしくお願いします。
確認ができたら、確認した旨のコメントをお願いします。
何か間違いがあったらご教示いただければと思います。
=> 予約情報登録完了追加

src/main/java/com/example/demo/controller/UserController.java, src/main/resources/templates/login.html, src/main/resources/templates/mypage.html, src/main/resources/templates/userEdit.html
=> ログインを押したさいいのURL追記

src/main/java/com/example/demo/controller/UserController.java, src/main/java/com/example/demo/repository/UserRepository.java, src/main/resources/templates/login.html
=> integerに変更

src/main/java/com/example/demo/controller/ReservationController.java, src/main/java/com/example/demo/entity/Reservation.java, src/main/resources/schema.sql, src/main/resources/static/CSS/modal.css, src/main/resources/templates/bookingList.html
予約の論理削除機能、予約確認画面・予約完了画面のモーダル作成を行いました。
頑張ってので見てください。確認できたら報告ください。
=> 論理的な予約キャンセル機能およびモーダル画面の作成

src/main/java/com/example/demo/controller/HotelController.java, src/main/java/com/example/demo/dto/HotelPlanDTO.java, src/main/java/com/example/demo/entity/Hotel.java, src/main/java/com/example/demo/repository/HotelRepository.java, src/main/resources/templates/hotel.html
=> 表示形式の変更、ソートとページネーションの追加

src/main/java/com/example/demo/controller/HotelController.java, src/main/resources/templates/detailHotel.html
=> ホテル詳細画面の価格表示修正、予約送信内容(パラメータ)の修正

src/main/java/com/example/demo/controller/UserController.java, src/main/resources/static/CSS/header.css, src/main/resources/static/CSS/userEdit.css, src/main/resources/templates/userEdit.html
=> userEdit-cssデザイン完成

src/main/resources/static/CSS/hotel.css, src/main/resources/templates/hotel.html
=> 検索画面の修正、ホテル一覧の表示CSSの追加

src/main/resources/static/CSS/form.css, src/main/resources/static/CSS/reservation.css, src/main/resources/static/CSS/style.css, src/main/resources/templates/register.html
@K-M0613 @mojito18 @m1k4226 
確認をよろしくお願いします。
=> 新規登録入力画面とログイン画面のUI修正

src/main/java/com/example/demo/repository/HotelRepository.java
=> プラン名でのキーワード検索を追加

src/main/java/com/example/demo/controller/ReservationController.java, src/main/resources/static/CSS/completion.css, src/main/resources/static/CSS/hotel.css, src/main/resources/templates/completeStayInfo.html, src/main/resources/templates/confirmStayInfo.html, src/main/resources/templates/sessionExpired.html
=> 予約完了画面のデザイン

src/main/resources/static/CSS/detailHotel.css, src/main/resources/templates/detailHotel.html
=> detail画面に大まかなCSSを追加

src/main/resources/static/CSS/hotel.css, src/main/resources/templates/hotel.html
=> カレンダーjsの復元、ページネーション下部の空白修正、ホテル名(リンク)に下線の追加など

src/main/resources/static/CSS/completion.css, src/main/resources/templates/registerComplete.html
=> 予約完了画面の写真追加と、テキストの調整などのCSS修正

src/main/resources/static/CSS/completion.css, src/main/resources/templates/completeStayInfo.html, src/main/resources/templates/registerComplete.html
=> 予約完了と登録完了のアニメーション、CSS統一化

src/main/java/com/example/demo/model/Account.java, src/main/resources/static/CSS/emailEdit.css, src/main/resources/static/CSS/mypage.css, src/main/resources/static/CSS/passwordEdit.css, src/main/resources/static/CSS/reset.css, src/main/resources/static/CSS/userEdit.css, src/main/resources/templates/emailEdit.html, src/main/resources/templates/mypage.html, src/main/resources/templates/reservationDetail.html
=> 戻るボタンなどの修正

src/main/resources/static/CSS/top.css
=> TOPの文字位置、写真位置の修正

src/main/resources/static/CSS/button.css, src/main/resources/templates/register.html, src/main/resources/templates/registerConfirm.html
=> 新規登録関連の『戻る』ボタンを統一化

src/main/resources/static/CSS/detailHotel.css
@K-M0613 @mshiina @m1k4226 
確認お願いします
=> detail-flex h3に変更
